# Hackathon Notebook

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
df = pd.read_csv('data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [3]:
df['date_added'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: date_added
Non-Null Count  Dtype
--------------  -----
8797 non-null   object
dtypes: object(1)
memory usage: 68.9+ KB

In [4]:
df_clean = df.copy()
df_clean = df_clean.dropna(subset=['date_added'])
df_clean['date_added'] = pd.to_datetime(df_clean['date_added'].str.lstrip(' '), format='%B %d, %Y')
df_clean['month_added'] = df_clean['date_added'].dt.month
df_clean['year_added'] = df_clean['date_added'].dt.year
df_clean.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,month_added,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",9,2021
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",9,2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,9,2021
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",9,2021
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,9,2021

In [5]:
df_clean['movie_duration'] = df_clean['duration'].apply(lambda x: int(x.split()[0]) if isinstance(x, str) and 'min' in x.lower() else np.nan)
df_clean['tv_show_seasons'] = df_clean['duration'].apply(lambda x: int(x.split()[0]) if isinstance(x, str) and 'Season' in x else np.nan) 
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8797 entries, 0 to 8806
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8797 non-null   object
 1   type             8797 non-null   object
 2   title            8797 non-null   object
 3   director         6173 non-null   object
 4   cast             7972 non-null   object
 5   country          7967 non-null   object
 6   date_added       8797 non-null   datetime64[ns]
 7   release_year     8797 non-null   int64
 8   rating           8793 non-null   object
 9   duration         8794 non-null   object
 10  listed_in        8797 non-null   object
 11  description      8797 non-null   object
 12  month_added      8797 non-null   int32
 13  year_added       8797 non-null   int32
 14  movie_duration   6128 non-null   float64
 15  tv_show_seasons  2666 non-null   float64
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(10)
memory usage: 1.1+ MB

In [6]:
df_clean.at[5541, 'movie_duration'] = 74
df_clean.at[5794, 'movie_duration'] = 84
df_clean.at[5813, 'movie_duration'] = 66

df_clean.at[5541, 'rating'] = 'Not Rated'
df_clean.at[5794, 'rating'] = 'Not Rated'
df_clean.at[5813, 'rating'] = 'Not Rated'

df_clean.at[5541, 'duration'] = '74 min'
df_clean.at[5794, 'duration'] = '84 min'
df_clean.at[5813, 'duration'] = '66 min'

# 5541 - 74
# 5794 - 84
# 5813 - 66

df_clean[(df_clean['type'] == 'Movie') & (df_clean['movie_duration'].isna())]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, month_added, year_added, movie_duration, tv_show_seasons]
Index: []

In [7]:
df_clean.reset_index(inplace=True, drop=True)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8797 entries, 0 to 8796
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8797 non-null   object
 1   type             8797 non-null   object
 2   title            8797 non-null   object
 3   director         6173 non-null   object
 4   cast             7972 non-null   object
 5   country          7967 non-null   object
 6   date_added       8797 non-null   datetime64[ns]
 7   release_year     8797 non-null   int64
 8   rating           8793 non-null   object
 9   duration         8797 non-null   object
 10  listed_in        8797 non-null   object
 11  description      8797 non-null   object
 12  month_added      8797 non-null   int32
 13  year_added       8797 non-null   int32
 14  movie_duration   6131 non-null   float64
 15  tv_show_seasons  2666 non-null   float64
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(10)
memory usage: 1.0+ MB

In [8]:
df_clean['country'].fillna('Unknown', inplace=True)
df_clean['rating'].fillna('Not Rated', inplace=True)
df_clean['duration'].fillna('Unknown', inplace=True)

df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8797 entries, 0 to 8796
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8797 non-null   object
 1   type             8797 non-null   object
 2   title            8797 non-null   object
 3   director         6173 non-null   object
 4   cast             7972 non-null   object
 5   country          8797 non-null   object
 6   date_added       8797 non-null   datetime64[ns]
 7   release_year     8797 non-null   int64
 8   rating           8797 non-null   object
 9   duration         8797 non-null   object
 10  listed_in        8797 non-null   object
 11  description      8797 non-null   object
 12  month_added      8797 non-null   int32
 13  year_added       8797 non-null   int32
 14  movie_duration   6131 non-null   float64
 15  tv_show_seasons  2666 non-null   float64
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(10)
memory usage: 1.0+ MB

/tmp/ipykernel_91/3068480811.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['country'].fillna('Unknown', inplace=True)
/tmp/ipykernel_91/3068480811.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['rating'].fillna('Not Rated', inplace=True)
/tmp/ipykernel_91/3068480811.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['duration'].fillna('Unknown', inplace=True)

In [9]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8797 entries, 0 to 8796
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8797 non-null   object
 1   type             8797 non-null   object
 2   title            8797 non-null   object
 3   director         6173 non-null   object
 4   cast             7972 non-null   object
 5   country          8797 non-null   object
 6   date_added       8797 non-null   datetime64[ns]
 7   release_year     8797 non-null   int64
 8   rating           8797 non-null   object
 9   duration         8797 non-null   object
 10  listed_in        8797 non-null   object
 11  description      8797 non-null   object
 12  month_added      8797 non-null   int32
 13  year_added       8797 non-null   int32
 14  movie_duration   6131 non-null   float64
 15  tv_show_seasons  2666 non-null   float64
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(10)
memory usage: 1.0+ MB

In [10]:
df_clean['cast'] = df_clean['cast'].str.split(', ')
df_clean['country'] = df_clean['country'].str.split(', ')
df_clean['listed_in'] = df_clean['listed_in'].str.split(', ')
df_clean.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,month_added,year_added,movie_duration,tv_show_seasons
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,[United States],2021-09-25,2020,PG-13,90 min,[Documentaries],"As her father nears the end of his life, filmm...",9,2021,90.0,NaN
1,s2,TV Show,Blood & Water,NaN,"[Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...",[South Africa],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, TV Dramas, TV Mysteries]","After crossing paths at a party, a Cape Town t...",9,2021,NaN,2.0
2,s3,TV Show,Ganglands,Julien Leclercq,"[Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nab...",[Unknown],2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV Ac...",To protect his family from a powerful drug lor...,9,2021,NaN,1.0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,[Unknown],2021-09-24,2021,TV-MA,1 Season,"[Docuseries, Reality TV]","Feuds, flirtations and toilet talk go down amo...",9,2021,NaN,1.0
4,s5,TV Show,Kota Factory,NaN,"[Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...",[India],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, Romantic TV Shows, TV...",In a city of coaching centers known to train I...,9,2021,NaN,2.0

In [11]:
# Define a function to assign minimum age based on rating
def get_minimum_age(rating):
    rating_mapping = {
        # Movie Ratings
        'G': 0,
        'PG': 7,
        'PG-13': 13,
        'R': 17,
        'NC-17': 18,
        'NR': 'Unknown',  # Not Rated can be treated as Unknown or NaN
        # TV Ratings
        'TV-Y': 0,
        'TV-Y7': 7,
        'TV-Y7-FV': 7,
        'TV-G': 0,
        'TV-PG': 13,
        'TV-14': 14,
        'TV-MA': 17,
        'UR': 'Unknown'  # Unrated can be treated as Unknown or NaN
    }
    # Return the mapped minimum age or 'Unknown' if the rating isn't recognized
    return rating_mapping.get(rating, 'Unknown')
 
# Apply the function to the 'rating' column to create a new column 'minimum_age'
df_clean['minimum_age'] = df_clean['rating'].apply(get_minimum_age)
 
# Check the result
df_clean.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,month_added,year_added,movie_duration,tv_show_seasons,minimum_age
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,[United States],2021-09-25,2020,PG-13,90 min,[Documentaries],"As her father nears the end of his life, filmm...",9,2021,90.0,NaN,13
1,s2,TV Show,Blood & Water,NaN,"[Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...",[South Africa],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, TV Dramas, TV Mysteries]","After crossing paths at a party, a Cape Town t...",9,2021,NaN,2.0,17
2,s3,TV Show,Ganglands,Julien Leclercq,"[Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nab...",[Unknown],2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV Ac...",To protect his family from a powerful drug lor...,9,2021,NaN,1.0,17
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,[Unknown],2021-09-24,2021,TV-MA,1 Season,"[Docuseries, Reality TV]","Feuds, flirtations and toilet talk go down amo...",9,2021,NaN,1.0,17
4,s5,TV Show,Kota Factory,NaN,"[Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...",[India],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, Romantic TV Shows, TV...",In a city of coaching centers known to train I...,9,2021,NaN,2.0,17

In [12]:
params = {
    'apikey': '7c64b226',
    't': 'Black Mirror: Bandersnatch'
         }
url = f'http://www.omdbapi.com/'

r = requests.get(url, params)

print(r.text)

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head><title>403 Filtered</title></head>
<body>
<h1>Filtered</h1>
<p>The request you made has been filtered</p>
<hr />
<p><em>Generated by tinyproxy version 1.11.0.</em></p>
</body>
</html>

In [13]:
df_clean[df_clean['movie_duration'] > 180][['movie_duration', 'title','description','director']].sort_values('movie_duration',ascending=False)

,movie_duration,title,description,director
4253,312.0,Black Mirror: Bandersnatch,"In 1984, a young programmer begins to question...",NaN
717,273.0,Headspace: Unwind Your Mind,"Do you want to relax, meditate or sleep deeply...",NaN
2491,253.0,The School of Mischief,A high school teacher volunteers to transform ...,Houssam El-Din Mustafa
2487,237.0,No Longer kids,Hoping to prevent their father from skipping t...,Samir Al Asfory
2484,233.0,Lock Your Girls In,A widower believes he must marry off his three...,Fouad El-Mohandes
2488,230.0,Raya and Sakina,When robberies and murders targeting women swe...,Hussein Kamal
166,229.0,Once Upon a Time in America,Director Sergio Leone's sprawling crime epic f...,Sergio Leone
7923,228.0,Sangam,Returning home from war after being assumed de...,Raj Kapoor
1019,224.0,Lagaan,"In 1890s India, an arrogant British commander ...",Ashutosh Gowariker
4573,214.0,Jodhaa Akbar,"In 16th-century India, what begins as a strate...",Ashutosh Gowariker
807,212.0,Seven Souls in the Skull Castle: Season Moon K...,"Japan, 1590. Wandering samurai band together t...",Hidenori Inoue
2731,209.0,Kabhi Khushi Kabhie Gham,Years after his father disowns his adopted bro...,Karan Johar
3227,209.0,The Irishman,Hit man Frank Sheeran looks back at the secret...,Martin Scorsese
2632,208.0,No Direction Home: Bob Dylan,Featuring rare concert footage and interviews ...,Martin Scorsese
8317,205.0,The Gospel of Luke,Word-for-word Bible texts of the entire book o...,David Batty
2483,204.0,Fifty Year Old Teenager,The life of a married 50-year-old doctor turns...,Fouad Al Shatti
806,204.0,Seven Souls in the Skull Castle: Season Moon J...,"Japan, 1590. Wandering samurai band together t...",Hidenori Inoue
2126,203.0,What's Your Raashee?,"To protect his family from ruin, Yogesh must m...",Ashutosh Gowariker
8394,201.0,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,Peter Jackson
6617,200.0,Doctor Zhivago,A young physician and his beautiful mistress g...,David Lean
6678,196.0,Elephants Dream 4 Hour,"Friends Proog and Emo live in a capricious, se...",Bassam Kurdali
2490,195.0,The Married Couples,"Hailing from different classes, a young man an...",Hassan AbdulSalam
7948,195.0,Schindler's List,Oskar Schindler becomes an unlikely humanitari...,Steven Spielberg
2373,194.0,Saladin,The Sultan of Egypt and Syria launches a campa...,Youssef Chahine
2957,193.0,Hum Aapke Hain Koun,"Although Nisha falls for Prem, she agrees to m...",Sooraj R. Barjatya
7380,192.0,Maine Pyar Kiya,When the son of a wealthy businessman and the ...,Sooraj R. Barjatya
2730,192.0,Kabhi Alvida Naa Kehna,"Unhappy in their respective marriages, an ex-f...",Karan Johar
8754,191.0,Wyatt Earp,Legendary lawman Wyatt Earp is continually at ...,Lawrence Kasdan
2543,190.0,Unbreakable Kimmy Schmidt: Kimmy vs. the Reverend,It's an interactive Kimmy special! Kimmy's get...,Claire Scanlon
8319,190.0,The Gospel of Matthew,The Apostle Matthew is highlighted in this wor...,David Batty
341,189.0,Magnolia,"Through chance, history and divine interventio...",Paul Thomas Anderson
2732,187.0,Kal Ho Naa Ho,An uptight MBA student falls for the charismat...,Nikkhil Advani
7698,187.0,Pardes,"Prompted by loyalty, Arjun plays matchmaker be...",Subhash Ghai
2843,186.0,Aurora,"42-year-old Viorel, a distraught engineer, tak...",Cristi Puiu
3131,185.0,Dil Chahta Hai,"Inseparable childhood friends Akash, Sameer an...",Farhan Akhtar
1132,185.0,Seven Souls in the Skull Castle: Season Wind,"Japan, 1590. Wandering samurai band together t...",Hidenori Inoue
2734,185.0,Kuch Kuch Hota Hai,"Per her mother’s last wish, a girl sets out to...",Karan Johar
5014,185.0,Swades,An Americanized NASA scientist returns to his ...,Ashutosh Gowariker
3142,185.0,Lakshya,"After dropping out of the army, a spoiled teen...",Farhan Akhtar
7522,185.0,Mutiny on the Bounty,Marlon Brando gives a nuanced performance as t...,"Lewis Milestone, Carol Reed"
1130,182.0,Seven Souls in the Skull Castle: Season Bird,"Japan, 1590. Wandering samurai band together t...",Hidenori Inoue
73,182.0,King of Boys,When a powerful businesswoman’s political ambi...,Kemi Adetiba
1247,182.0,Banyuki,In this stage performance filmed for the big s...,Hidenori Inoue
1131,181.0,Seven Souls in the Skull Castle: Season Flower,"Japan, 1590. Wandering samurai band together t...",Hidenori Inoue
6744,181.0,Fiddler on the Roof,This adaptation of the musical chronicles the ...,Norman Jewison
1251,181.0,Dances with Wolves,"On the frontier, a Civil War soldier bonds wit...",Kevin Costner
7128,181.0,Jis Desh Men Ganga Behti Hai,Falling in with a band of outlaws during a hol...,Radhu Karmakar